### ISSUE TITLE
Stylesheets not showing properties in epub

### ISSUE THREAD

**Issue by amit34521** [dreamer2908/Baka-Epub#1]
When reading on mobile, none of the effects from the stylesheets work such as centered headings etc for epubs made with the script. but if i do it manually, no problems occur. Can anyone help please??

**Comment by dreamer2908** [comment]
Stylesheet is an important feature that any decent epub reader should support. If the app you're using on your phone has problems with it, you might as well search for a better one. 
I have no smartphone so I can't help you.

**Comment by amit34521** [comment]
i have old epubs and the stylesheets are working well in them. only the ones made with your script aren't working well in mobile.

**Comment by dreamer2908** [comment]
Please check the newly-made epubs with EpubCheck (online version for files under 10 MB [here](http://validator.idpf.org/)) and [FlightCrew plugins for Sigil](https://github.com/Sigil-Ebook/flightcrew/releases). 
I will do something if they report any errors or warnings*. Otherwise, the files are 100% standards-compliant, perfect in the technical sense, so they can't be fixed.

Or maybe you should seriously listen to my recommendation and use WebToEpub instead.
I really don't want to support any user other than myself.

`*` Except for FlightCrew warning about file Section0001.xhtml (empty) unused. The script doesn't delete it automatically because on some systems, Sigil will crash if it does that. It can be removed manually or let alone.
